---
abstract: 'Manipulate IPv4/IPv6 netblocks in CIDR notation'
author:
  - 'Sam Varshavchik <sam@email-scan.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.46, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-CIDR
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
version: '0.21'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
